// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io/fs"

	"github.com/matlab/matlab-mcp-core-server/tests/testutils/mcpbundle/unpack"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileSystem creates a new instance of MockFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystem {
	mock := &MockFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileSystem is an autogenerated mock type for the FileSystem type
type MockFileSystem struct {
	mock.Mock
}

type MockFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystem) EXPECT() *MockFileSystem_Expecter {
	return &MockFileSystem_Expecter{mock: &_m.Mock}
}

// MkdirAll provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) MkdirAll(path string, perm fs.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileSystem_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileSystem_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *MockFileSystem_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFileSystem_MkdirAll_Call {
	return &MockFileSystem_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFileSystem_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *MockFileSystem_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileMode
		if args[1] != nil {
			arg1 = args[1].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) Return(err error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) RunAndReturn(run func(path string, perm fs.FileMode) error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type MockFileSystem
func (_mock *MockFileSystem) OpenFile(name string, flag int, perm fs.FileMode) (unpack.WriteCloser, error) {
	ret := _mock.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 unpack.WriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, fs.FileMode) (unpack.WriteCloser, error)); ok {
		return returnFunc(name, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, fs.FileMode) unpack.WriteCloser); ok {
		r0 = returnFunc(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(unpack.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, fs.FileMode) error); ok {
		r1 = returnFunc(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileSystem_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type MockFileSystem_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm fs.FileMode
func (_e *MockFileSystem_Expecter) OpenFile(name interface{}, flag interface{}, perm interface{}) *MockFileSystem_OpenFile_Call {
	return &MockFileSystem_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *MockFileSystem_OpenFile_Call) Run(run func(name string, flag int, perm fs.FileMode)) *MockFileSystem_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileSystem_OpenFile_Call) Return(writeCloser unpack.WriteCloser, err error) *MockFileSystem_OpenFile_Call {
	_c.Call.Return(writeCloser, err)
	return _c
}

func (_c *MockFileSystem_OpenFile_Call) RunAndReturn(run func(name string, flag int, perm fs.FileMode) (unpack.WriteCloser, error)) *MockFileSystem_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}
