// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/tests/testutils/mcpbundle"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandRunner creates a new instance of MockCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandRunner {
	mock := &MockCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandRunner is an autogenerated mock type for the CommandRunner type
type MockCommandRunner struct {
	mock.Mock
}

type MockCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandRunner) EXPECT() *MockCommandRunner_Expecter {
	return &MockCommandRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) Run(ctx context.Context, launcherPath string, env []string) (mcpbundle.LaunchResult, error) {
	ret := _mock.Called(ctx, launcherPath, env)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 mcpbundle.LaunchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (mcpbundle.LaunchResult, error)); ok {
		return returnFunc(ctx, launcherPath, env)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) mcpbundle.LaunchResult); ok {
		r0 = returnFunc(ctx, launcherPath, env)
	} else {
		r0 = ret.Get(0).(mcpbundle.LaunchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, launcherPath, env)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - launcherPath string
//   - env []string
func (_e *MockCommandRunner_Expecter) Run(ctx interface{}, launcherPath interface{}, env interface{}) *MockCommandRunner_Run_Call {
	return &MockCommandRunner_Run_Call{Call: _e.mock.On("Run", ctx, launcherPath, env)}
}

func (_c *MockCommandRunner_Run_Call) Run(run func(ctx context.Context, launcherPath string, env []string)) *MockCommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommandRunner_Run_Call) Return(launchResult mcpbundle.LaunchResult, err error) *MockCommandRunner_Run_Call {
	_c.Call.Return(launchResult, err)
	return _c
}

func (_c *MockCommandRunner_Run_Call) RunAndReturn(run func(ctx context.Context, launcherPath string, env []string) (mcpbundle.LaunchResult, error)) *MockCommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
